Fix an incorrect error check.
covscan says:
Error: REVERSE_INULL (CWE-476): [#def18]
libsmbios-2.3.3/src/libsmbios_c/memory/memory_linux.c:260: deref_ptr: Directly dereferencing pointer "private_data".
libsmbios-2.3.3/src/libsmbios_c/memory/memory_linux.c:262: check_after_deref: Null-checking "private_data" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.

And it's right; private_data->filename has been assigned to between
allocating private_data and checking for success.  Also the free() path
on the error pathway has some invalid reference possibilities in it.

It also says:

Error: FORWARD_NULL (CWE-476): [#def19]
libsmbios-2.3.3/src/libsmbios_c/memory/memory_linux.c:262: var_compare_op: Comparing "private_data->filename" to null implies that "private_data->filename" might be null.
libsmbios-2.3.3/src/libsmbios_c/memory/memory_linux.c:291: var_deref_model: Passing null pointer "private_data->filename" to "strlcat", which dereferences it.
libsmbios-2.3.3/src/libsmbios_c/common/strlcat.c:34:19: var_assign_parm: Assigning: "s" = "src".
libsmbios-2.3.3/src/libsmbios_c/common/strlcat.c:45:9: deref_var_in_call: Function "strlen" dereferences "s" (which is a copy of "src").

And we can just use fn here instead.

So this patch fixes all that up.

Signed-off-by: Peter Jones <pjones@redhat.com>