Fix two pointer arithmetic errors.
Covscan noticed:
Error: SIZEOF_MISMATCH (CWE-398): [#def44]
libsmbios-2.3.3/src/libsmbios_c/token/token_d4.c:321: suspicious_pointer_arithmetic: Adding "5UL /* sizeof (*token) */" to pointer "token" of type "struct indexed_io_token *" is suspicious because adding an integral value to this pointer automatically scales that value by the size, 5 bytes, of the pointed-to type, "struct indexed_io_token".  Most likely, "sizeof (*token)" is extraneous and should be replaced with 1.

Error: SIZEOF_MISMATCH (CWE-398): [#def45]
libsmbios-2.3.3/src/libsmbios_c/token/token_da.c:212: suspicious_pointer_arithmetic: Adding "6UL /* sizeof (*token) */" to pointer "token" of type "struct calling_interface_token *" is suspicious because adding an integral value to this pointer automatically scales that value by the size, 6 bytes, of the pointed-to type, "struct calling_interface_token".  Most likely, "sizeof (*token)" is extraneous and should be replaced with 1.

It's right, both of these are checking if they're past the last element,
so 1 should be used.

Signed-off-by: Peter Jones <pjones@redhat.com>