sysinfo_get_dell_oem_system_id(): don't look at the wrong array.
Covscan noticed:
Error: OVERRUN (CWE-119): [#def40]
libsmbios-2.3.3/src/libsmbios_c/system_info/id_byte.c:219: assignment: Assigning: "numEntries" = "5".
libsmbios-2.3.3/src/libsmbios_c/system_info/id_byte.c:223: cond_at_most: Checking "i < numEntries" implies that "i" may be up to 4 on the true branch.
libsmbios-2.3.3/src/libsmbios_c/system_info/id_byte.c:225: overrun-local: Overrunning array "DellIdByteFunctions" of 4 16-byte elements at element index 4 (byte offset 64) using index "i" (which evaluates to 4).

What it didn't notice is that DellIdByteFunctions is the wrong array
entirely, which is why it's the wrong offset.  It should really notice
that.  Oh well.

Anyway, this patch makes it use the correct array.

Signed-off-by: Peter Jones <pjones@redhat.com>