Fix some plausible buffer overruns.
Covscan noticed these:

Error: STRING_OVERFLOW (CWE-120): [#def28]
libsmbios-2.3.3/src/libsmbios_c/smi/smi_linux.c:128: fixed_size_dest: You might overrun the 256-character fixed-size string "fn" by copying "sysfs_basedir" without checking the length.

Error: STRING_OVERFLOW (CWE-120): [#def29]
libsmbios-2.3.3/src/libsmbios_c/smi/smi_linux.c:129: fixed_size_dest: You might overrun the 256-character fixed-size string "fn" by copying "smi_data_fn" without checking the length.

Error: STRING_OVERFLOW (CWE-120): [#def30]
libsmbios-2.3.3/src/libsmbios_c/smi/smi_linux.c:170: fixed_size_dest: You might overrun the 256-character fixed-size string "fn" by copying "sysfs_basedir" without checking the length.

Error: STRING_OVERFLOW (CWE-120): [#def31]
libsmbios-2.3.3/src/libsmbios_c/smi/smi_linux.c:171: fixed_size_dest: You might overrun the 256-character fixed-size string "fn" by copying "smi_data_fn" without checking the length.

Error: STRING_OVERFLOW (CWE-120): [#def32]
libsmbios-2.3.3/src/libsmbios_c/smi/smi_linux.c:188: fixed_size_dest: You might overrun the 256-character fixed-size string "fn" by copying "sysfs_basedir" without checking the length.

Error: STRING_OVERFLOW (CWE-120): [#def33]
libsmbios-2.3.3/src/libsmbios_c/smi/smi_linux.c:189: fixed_size_dest: You might overrun the 256-character fixed-size string "fn" by copying "smi_request_fn" without checking the length.

I don't know how big they can actually be - it depends on what
sysfs_basedir winds up being, which I imagine is smallish so long as
sysfs is on /sys, but it doesn't need to be - but I think covscan is
right, if impractical.

This patch replaces all of these with an allocate_path(a, b) call that
allocates the correct amount of space on the stack and copies the data
in.

Signed-off-by: Peter Jones <pjones@redhat.com>