sysinfo_get_asset_tag(): get rid of a strncpy() off by one error.
Covscan found:

Error: BUFFER_SIZE (CWE-120): [#def39]
libsmbios-2.3.3/src/libsmbios_c/system_info/asset_tag.c:143: buffer_size: Calling strncpy with a source string whose length (13 chars) is greater than or equal to the size argument (13) will fail to null-terminate "assetTag".

In which case the buffer would not be correctly terminated.  This loop
also returns the /first/ zero-length entry instead of trying additional
methods, as the comment at the top implies it should do.

This patch simplifies the loop, and simply returns
strdup(ASSET_TAG_NOT_SPECIFIED) in the case where we find no useful
response.

Signed-off-by: Peter Jones <pjones@redhat.com>