smbios_strerror: Always return a valid string
There were two problems here

  - smbios_table_free () frees the error string, meaning we returned
    something that was subject to use-after-free violations
  - smbios_table_factory () can fail, meaning we have no good string to
    return there. The return value is going to be given to strlcat (),
    which can't take NULL.

Fix the first one by strdupping the returned string, and the second by
returning the empty string. In the first case this is a leak, since we
are 'const char'. We could also fix this by making the strings returned
by smbios_table_strerror () never freed.