memory_linux.c:remap() fix some types to avoid comparison sign mismatches
struct linux_data, remap(), and trycopy() have types that don't have
matching signs for no good reason, and this is noticed if you build with
-Wsign-compare (enabled by the quite wonderful -Wextra in recent gcc).
Right now these are the only thing in the tree that fail with "gcc -Wall
-Wextra -Werror":

libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -I./out/include -I./out/include -I../src/include -DLIBSMBIOS_LOCALEDIR=\"/usr/share/locale\" -I../src/libsmbios_c/common -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -fPIC -fvisibility=hidden -Werror -c ../src/libsmbios_c/system_info/system_info.c  -fPIC -DPIC -o src/libsmbios_c/system_info/.libs/out_libsmbios_c_la-system_info.o
../src/libsmbios_c/memory/memory_linux.c: In function 'trycopy':
../src/libsmbios_c/memory/memory_linux.c:134:24: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
     if( length + mmoff > (private_data->mappingSize) )
                        ^
and

libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I./out/include -I./out/include -I./src/include -DLIBSMBIOS_LOCALEDIR=\"/usr/local/share/locale\" -I./src/libsmbios_c/common -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -fPIC -fvisibility=hidden -Wall -Werror -Wextra -DLIBSMBIOS_C_ALL_DYN_LINK -MT src/libsmbios_c/memory/out_libsmbios_c_la-memory_linux.lo -MD -MP -MF src/libsmbios_c/memory/.deps/out_libsmbios_c_la-memory_linux.Tpo -c src/libsmbios_c/memory/memory_linux.c  -fPIC -DPIC -o src/libsmbios_c/memory/.libs/out_libsmbios_c_la-memory_linux.o
src/libsmbios_c/memory/memory_linux.c: In function ‘remap’:
src/libsmbios_c/memory/memory_linux.c:109:22: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
     if (offset-mmoff == private_data->lastMappedOffset)
                      ^~

This fixes them to use off_t and size_t as appropriate.

Signed-off-by: Peter Jones <pjones@redhat.com>